from pyspark.sql import SparkSession
spark=SparkSession.builder.appName('demo').getOrCreate()
import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt
df2=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/police/2017 Cases against Police Personnels.csv",inferSchema=True)
df2.show()
df2.printSchema()
df1=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/police/2016 Cases against Police Personnels.csv",inferSchema=True)
df1.show()
df1.printSchema()
df3=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/police/2018 Cases against Police Personnels.csv",inferSchema=True)
df3.show()
df3.printSchema()
df4=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/escape/2016 Escapes from Police Custody.csv",inferSchema=True)
df4.show()
df4.printSchema()
df5=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/escape/2017 Escapes from Police Custody.csv",inferSchema=True)
df5.show()
df5.printSchema()
df6=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/escape/2018 Escapes from Police Custody.csv",inferSchema=True)
df6.show()
df6.printSchema()
df7=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/rape/2016 Victims of Rape.csv",inferSchema=True)
df7.show()
df7.printSchema()
df8=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/rape/2017 Victims of Rape.csv",inferSchema=True)
df8.show()
df8.printSchema()
df9=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/rape/2018 Victims of Rape.csv",inferSchema=True)
df9.show()
df9.printSchema()
women_ab2018=df9.select('State/UT ','Women Victims of Rape (Above 18 Yrs) - Total Women/Adult Victims')
women_ab2018.show()
total_women_ab2018=women_ab2018.withColumnRenamed('Women Victims of Rape (Above 18 Yrs) - Total Women/Adult Victims','women_rape_victim_2018')
total_women_ab2018.show()
final_totalwomen_rape2018=total_women_ab2018.sort(total_women_ab2018['women_rape_victim_2018'].desc())
final_totalwomen_rape2018.show()
worst_10state_abusedwomen_2018=final_totalwomen_rape2018.limit(5)
worst_10state_abusedwomen_2018.show()
for_pie_worst_states = worst_10state_abusedwomen_2018.toPandas()
for_pie_worst_states.set_index('State/UT ',inplace=True)
for_pie_worst_states.plot(kind='pie', y="women_rape_victim_2018", figsize=(10, 5))
plt.xlabel('State')
plt.ylabel("women rape")
plt.title("worst 5 state in women rape")
plt.legend(for_pie_worst_states.index,title='States')
plt.xticks(rotation=90)
plt.show()