from pyspark.sql import SparkSession
spark=SparkSession.builder.appName('demo').getOrCreate()
import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt
df2=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/police/2017 Cases against Police Personnels.csv",inferSchema=True)
df2.show()
df2.printSchema()
df1=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/police/2016 Cases against Police Personnels.csv",inferSchema=True)
df1.show()
df1.printSchema()
df3=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/police/2018 Cases against Police Personnels.csv",inferSchema=True)
df3.show()
df3.printSchema()
df4=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/escape/2016 Escapes from Police Custody.csv",inferSchema=True)
df4.show()
df4.printSchema()
df5=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/escape/2017 Escapes from Police Custody.csv",inferSchema=True)
df5.show()
df5.printSchema()
df6=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/escape/2018 Escapes from Police Custody.csv",inferSchema=True)
df6.show()
df6.printSchema()
df7=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/rape/2016 Victims of Rape.csv",inferSchema=True)
df7.show()
df7.printSchema()
df8=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/rape/2017 Victims of Rape.csv",inferSchema=True)
df8.show()
df8.printSchema()
df9=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/rape/2018 Victims of Rape.csv",inferSchema=True)
df9.show()
df9.printSchema()
victims_3year=df7.join(df9,'S. No')
victims_3year.show(50)
final_3year_victim=victims_3year.drop('S. No','State/UT ','Child Victims of Rape (Below 18 Yrs) - 6 Years & Above ','Child Victims of Rape (Below 18 Yrs) - 12 Years & Above ','Child Victims of Rape (Below 18 Yrs) - 16 Years & Above ','','Category','Cases Reported','Child Victims of Rape (Below 18 Yrs) - Below 6 Years','Child Victims of Rape (Below 18 Yrs) - 6 Years & Above - Below 12 Years','Child Victims of Rape (Below 18 Yrs) - 12 Years & Above - Below 16 Years','Child Victims of Rape (Below 18 Yrs) - 16 Years & Above - Below 18 Years','Women Victims of Rape (Above 18 Yrs) - 18 Years & Above - Below 30 Years','Women Victims of Rape (Above 18 Yrs) - 30 Years & Above - Below 45 Years','Women Victims of Rape (Above 18 Yrs) - 45 Years & Above - Below 60 Years','Women Victims of Rape (Above 18 Yrs) - 60 Years & Above','Women Victims of Rape (Above 18 Yrs) - Total Women/Adult Victims','Total Victims')

final_vic1=final_3year_victim.withColumnRenamed('Child Victims of Rape (Below 18 Yrs) - Total Girl/Child Victims','total child victims in 2018')
final_3year_victim.show()
final_vic1.show()
final_vic2=final_vic1.withColumnRenamed('Child Victims of Rape (Below 18 Yrs) - Total Girl /Child Victims','child victim in 2016')
final_vic2.show()
final_vic2.toPandas().plot(kind='bar' , x='State/UT' , y= 'child victim in 2016',  figsize=(20, 10))
final_vic2.toPandas().plot(kind='bar' , x='State/UT' , y= 'total child victims in 2018',  figsize=(20, 10))
plt.xlabel('State')
plt.ylabel("child faced rape")
plt.title("child rape")
plt.xticks(rotation=90)
plt.show()
new_df=final_vic2.toPandas()
print(new_df)
new_df.plot(x='State/UT',y=['child victim in 2016','total child victims in 2018'],kind='bar',figsize=(10,5))
plt.show()