from pyspark.sql import SparkSession
spark=SparkSession.builder.appName('demo').getOrCreate()
import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt
df2=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/police/2017 Cases against Police Personnels.csv",inferSchema=True)
df2.show()
df2.printSchema()
df1=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/police/2016 Cases against Police Personnels.csv",inferSchema=True)
df1.show()
df1.printSchema()
df3=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/police/2018 Cases against Police Personnels.csv",inferSchema=True)
df3.show()
df3.printSchema()
df4=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/escape/2016 Escapes from Police Custody.csv",inferSchema=True)
df4.show()
df4.printSchema()
df5=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/escape/2017 Escapes from Police Custody.csv",inferSchema=True)
df5.show()
df5.printSchema()
df6=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/escape/2018 Escapes from Police Custody.csv",inferSchema=True)
df6.show()
df6.printSchema()
df7=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/rape/2016 Victims of Rape.csv",inferSchema=True)
df7.show()
df7.printSchema()
df8=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/rape/2017 Victims of Rape.csv",inferSchema=True)
df8.show()
df8.printSchema()
df9=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/rape/2018 Victims of Rape.csv",inferSchema=True)
df9.show()
df9.printSchema()
out1=df1.select('State/UT','Total Number of Criminal Cases Registered during the year')
out1.show()
out1.toPandas().plot(kind='bar' , x='State/UT' , y= 'Total Number of Criminal Cases Registered during the year' ,color='green',figsize=(20, 10))
plt.xlabel('State')
plt.ylabel("Total Number of Criminal Cases Registered during the year 2016")
plt.title("Total Number of Criminal Cases against police Registered during the year 2016")
plt.xticks(rotation=90)
plt.show()