from pyspark.sql import SparkSession
spark=SparkSession.builder.appName('demo').getOrCreate()
df2=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/police/2017 Cases against Police Personnels.csv",inferSchema=True)
df2.show()
df2.printSchema()
df1=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/police/2016 Cases against Police Personnels.csv",inferSchema=True)
df1.show()
df1.printSchema()
df3=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/police/2018 Cases against Police Personnels.csv",inferSchema=True)
df3.show()
df3.printSchema()
df4=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/escape/2016 Escapes from Police Custody.csv",inferSchema=True)
df4.show()
df4.printSchema()
df5=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/escape/2017 Escapes from Police Custody.csv",inferSchema=True)
df5.show()
df5.printSchema()
df6=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/escape/2018 Escapes from Police Custody.csv",inferSchema=True)
df6.show()
df6.printSchema()
df7=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/rape/2016 Victims of Rape.csv",inferSchema=True)
df7.show()
df7.printSchema()
df8=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/rape/2017 Victims of Rape.csv",inferSchema=True)
df8.show()
df8.printSchema()
df9=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/rape/2018 Victims of Rape.csv",inferSchema=True)
df9.show()
df9.printSchema()
df1.write.format('csv').save('hdfs://localhost:9000/prodir1')
df2.write.format('csv').save('hdfs://localhost:9000/prodir2')
df3.write.format('csv').save('hdfs://localhost:9000/prodir3')
df4.write.format('csv').save('hdfs://localhost:9000/prodir4')
df5.write.format('csv').save('hdfs://localhost:9000/prodir5')
df6.write.format('csv').save('hdfs://localhost:9000/prodir6')
df7.write.format('csv').save('hdfs://localhost:9000/prodir7')
df8.write.format('csv').save('hdfs://localhost:9000/prodir8')
df9.write.format('csv').save('hdfs://localhost:9000/prodir9')
