from pyspark.sql import SparkSession
spark=SparkSession.builder.appName('demo').getOrCreate()
import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt
df2=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/police/2017 Cases against Police Personnels.csv",inferSchema=True)
df2.show()
df2.printSchema()
df1=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/police/2016 Cases against Police Personnels.csv",inferSchema=True)
df1.show()
df1.printSchema()
df3=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/police/2018 Cases against Police Personnels.csv",inferSchema=True)
df3.show()
df3.printSchema()
df4=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/escape/2016 Escapes from Police Custody.csv",inferSchema=True)
df4.show()
df4.printSchema()
df5=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/escape/2017 Escapes from Police Custody.csv",inferSchema=True)
df5.show()
df5.printSchema()
df6=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/escape/2018 Escapes from Police Custody.csv",inferSchema=True)
df6.show()
df6.printSchema()
df7=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/rape/2016 Victims of Rape.csv",inferSchema=True)
df7.show()
df7.printSchema()
df8=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/rape/2017 Victims of Rape.csv",inferSchema=True)
df8.show()
df8.printSchema()
df9=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/rape/2018 Victims of Rape.csv",inferSchema=True)
df9.show()
df9.printSchema()
number_person_escaped_2016=df4.select('State/UT','Total Number of Persons Escaped from Police Custody')
number_person_escaped_2016.show()
number_person_escaped_2016_renamed=number_person_escaped_2016.withColumnRenamed('Total Number of Persons Escaped from Police Custody','Total Number of persons_2016')
number_person_escaped_2016_renamed.show()
number_person_escaped_2017=df5.select('State/UT','Persons Escaped - Total')
number_person_escaped_2017_renamed=number_person_escaped_2017.withColumnRenamed('Persons Escaped - Total','Total Number of persons_2017')
number_person_escaped_2018=df6.select('State/UT','Persons Escaped - Total')
number_person_escaped_2018_renamed=number_person_escaped_2018.withColumnRenamed('Persons Escaped - Total','Total Number of persons_2018')
number_person_escaped_2016_join=number_person_escaped_2016_renamed.join(number_person_escaped_2017_renamed,'State/UT')
number_person_escaped_join=number_person_escaped_2016_join.join(number_person_escaped_2018_renamed,'State/UT')
number_person_escaped_join.show()
total_number_person_escaped=number_person_escaped_join.withColumn('Total_number_person_escaped',((number_person_escaped_2016_renamed['Total Number of persons_2016'])+(number_person_escaped_2017_renamed['Total Number of persons_2017'])+(number_person_escaped_2018_renamed['Total Number of persons_2018'])))
total_number_person_escaped.show()
escaped_persons_in_states=total_number_person_escaped.select('State/UT','Total_number_person_escaped')
escaped_persons_in_states.show()
least_escapedno_states=escaped_persons_in_states.sort(escaped_persons_in_states['Total_number_person_escaped'].asc())
least_escapedno_10_states=least_escapedno_states.limit(10)
least_escapedno_10_states.show()
for_pie_leastescape_states = least_escapedno_10_states.toPandas()
for_pie_leastescape_states.set_index('State/UT',inplace=True)
for_pie_leastescape_states.plot(kind='pie', y="Total_number_person_escaped", figsize=(10, 5))
plt.xlabel('State')
plt.ylabel("escaped_person")
plt.title("states where least prisoner escape")
plt.legend(for_pie_leastescape_states.index,title='States')
plt.xticks(rotation=90)
plt.show()