from pyspark.sql import SparkSession
spark=SparkSession.builder.appName('demo').getOrCreate()
import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt
df2=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/police/2017 Cases against Police Personnels.csv",inferSchema=True)
df2.show()
df2.printSchema()
df1=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/police/2016 Cases against Police Personnels.csv",inferSchema=True)
df1.show()
df1.printSchema()
df3=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/police/2018 Cases against Police Personnels.csv",inferSchema=True)
df3.show()
df3.printSchema()
df4=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/escape/2016 Escapes from Police Custody.csv",inferSchema=True)
df4.show()
df4.printSchema()
df5=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/escape/2017 Escapes from Police Custody.csv",inferSchema=True)
df5.show()
df5.printSchema()
df6=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/escape/2018 Escapes from Police Custody.csv",inferSchema=True)
df6.show()
df6.printSchema()
df7=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/rape/2016 Victims of Rape.csv",inferSchema=True)
df7.show()
df7.printSchema()
df8=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/rape/2017 Victims of Rape.csv",inferSchema=True)
df8.show()
df8.printSchema()
df9=spark.read.options(sep=',',header=True).csv("/home/admin1/Downloads/crime/rape/2018 Victims of Rape.csv",inferSchema=True)
df9.show()
df9.printSchema()
total_police_personals=df1.join(df2,'State/UT')
total_police_personals.show()
total_police_personals.printSchema()
final_convicted_police_allyear=total_police_personals.join(df3,'State/UT')
final_convicted_police_allyear.show()
final_convicted_police_allyear.printSchema()
all_year_convicted_police=final_convicted_police_allyear.select('State/UT',df3['Number of Police Personel - Convicted'],total_police_personals['Number of Police Personel - Convicted'],total_police_personals['Police Personnel Convicted'])
all_year_convicted_police.show()
final_all_year_convicted_police=all_year_convicted_police.withColumn('Total_convicted_police',((df3['Number of Police Personel - Convicted'])+(total_police_personals['Number of Police Personel - Convicted'])+(total_police_personals['Police Personnel Convicted'])))
final_all_year_convicted_police.show()
ftotal_all_year_convicted_police=final_all_year_convicted_police.select('State/UT','Total_convicted_police')
ordered_total_all_year_convicted_police=ftotal_all_year_convicted_police.sort(ftotal_all_year_convicted_police['Total_convicted_police'].desc())
ordered_total_all_year_convicted_police.show( )
most10_states_whr_police_convicted_in3years=ordered_total_all_year_convicted_police.limit(10)
most10_states_whr_police_convicted_in3years.show()
most10_states_whr_police_convicted_in3years.toPandas().plot(kind='bar' , x='State/UT', y='Total_convicted_police', color='r',figsize=(20, 10))
plt.show()